### ISSUE TITLE
Incorrect query in Chapter 09

### ISSUE THREAD

**Issue by sathishvj** [PacktPublishing/Machine-Learning-with-BigQuery-ML#1]
https://github.com/PacktPublishing/Machine-Learning-with-BigQuery-ML/blob/3e6a80569794cb75de6667898b9788247ba8abee/Chapter09/09_matrix_factorization.sql#L36

Query seems to be wrong.  I think this should be the correct query. 

```
SELECT
  *
FROM
  ML.EVALUATE(MODEL `09_recommendation_engine.purchase_recommender`,
    (
    SELECT * FROM `09_recommendation_engine.product_purchases`));
```

**Comment by ManikandanKurup-Packt** [comment]
Hi @sathishvj 
Thank you for your insights. This book is still in production so these are not finalized. But we'll surely have a look into it.

**Comment by alessandromarrandino** [comment]
Hi @sathishvj,
thanks for your comment. I've double checked and the query runs in a proper way (see screenshot below)
![image](https://user-images.githubusercontent.com/35006921/117429757-a4e52c80-af27-11eb-98df-40ed8b1c0ab5.png)

**Comment by sathishvj** [comment]
I don't remember this much now, but what is the "product_visits" table?  It has not been seen before.
