### ISSUE TITLE
Chapter 13: Add gcloud/gsutil commands also for convenience

### ISSUE THREAD

**Issue by sathishvj** [PacktPublishing/Machine-Learning-with-BigQuery-ML#2]
https://github.com/PacktPublishing/Machine-Learning-with-BigQuery-ML/blob/3e6a80569794cb75de6667898b9788247ba8abee/Chapter13/bqml_export_import.sql#L51

For convenience, the steps to create the Cloud Storage buckets could also be listed here.

**Comment by alessandromarrandino** [comment]
Hi @sathishvj ,
since the file is a SQL script, I prefer to keep separate the creation of the GCS bucket from the command line and the SQL queries to run on BigQuery.
