### ISSUE TITLE
Chapter 3: Linear regression ... stations names?

### ISSUE THREAD

**Issue by kolban-google** [PacktPublishing/Machine-Learning-with-BigQuery-ML#3]
I have a question.  I read chapter 4 on linear regression using the CitiBikes story.  I'm at a loss to understand how using the string place names of the start and end locations could ever be used as features for linear regression?  I don't think there is an underlying set of equations that could be used to predict duration given two textual names.

**Comment by sathyarams** [comment]
@kolban-google https://cloud.google.com/bigquery-ml/docs/reference/standard-sql/bigqueryml-auto-preprocessing should provide an explanation. 
For linear regression, all non-numeric values will be one-hot encoded.
